POST http://localhost:7071/api/travel/run HTTP/1.1
Content-Type: text/plain

I want to fly from New York to Paris on July 15th, departing in the morning.

###
POST http://localhost:7071/api/travel/choice/ce818b76fdcb4c4fbb36f87e862685c5 HTTP/1.1
Content-Type: text/plain

I approve the third option.


###
GET http://localhost:7071/api/travel/status/<instanceId> HTTP/1.1
